# Arquivo: docker-compose.yml

version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres_db:
    image: postgres:15-alpine
    container_name: plataforma_saude_postgres
    environment:
      POSTGRES_USER: postgres      # Usuário do banco
      POSTGRES_PASSWORD: docker    # Senha do banco
      POSTGRES_DB: plataforma_saude_db # Nome do banco que será criado automaticamente
    ports:
      - "5432:5432" # Expõe a porta do container para o seu computador
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Serviço do Redis
  redis_cache:
    image: redis:7-alpine
    container_name: plataforma_saude_redis
    ports:
      - "6379:6379" # Expõe a porta do Redis
    restart: unless-stopped

volumes:
  postgres_data: