"""Adiciona a tabela SolicitacaoCorrecao para o portal do titular

Revision ID: 10dcfea516df
Revises: e8f36eafdd07
Create Date: 2025-07-23 13:25:32.161426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dcfea516df'
down_revision = 'e8f36eafdd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_correcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('analisado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_analise', sa.DateTime(), nullable=True),
    sa.Column('resposta_gestor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analisado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacao_correcao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacao_correcao_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_correcao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacao_correcao_status'))

    op.drop_table('solicitacao_correcao')
    # ### end Alembic commands ###
