"""Adiciona tabela LogUso

Revision ID: 2143bd6ebe02
Revises: 7fee99ed99e7
Create Date: 2025-07-20 14:48:09.478026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2143bd6ebe02'
down_revision = '7fee99ed99e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('related_consulta_id', sa.Integer(), nullable=True),
    sa.Column('related_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_consulta_id'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['related_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_uso_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_uso_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_uso_timestamp'))
        batch_op.drop_index(batch_op.f('ix_log_uso_event_type'))

    op.drop_table('log_uso')
    # ### end Alembic commands ###
