"""Criação inicial das tabelas

Revision ID: 41f49ca81589
Revises: 
Create Date: 2025-07-20 10:11:53.106864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f49ca81589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('cns', sa.String(length=15), nullable=True),
    sa.Column('telefone_whatsapp', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone_whatsapp')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paciente_cns'), ['cns'], unique=True)
        batch_op.create_index(batch_op.f('ix_paciente_cpf'), ['cpf'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('termo_consentimento_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('versao_termo', sa.String(length=20), nullable=False),
    sa.Column('timestamp_aceite', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termo_consentimento_log')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_cpf'))
        batch_op.drop_index(batch_op.f('ix_paciente_cns'))

    op.drop_table('paciente')
    # ### end Alembic commands ###
