"""Adiciona tabela MensagemChatbot

Revision ID: 6b0d7361c6f3
Revises: c3ece67ceaf6
Create Date: 2025-07-20 12:23:03.575128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0d7361c6f3'
down_revision = 'c3ece67ceaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem_chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagem_chatbot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagem_chatbot_chave'), ['chave'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem_chatbot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagem_chatbot_chave'))

    op.drop_table('mensagem_chatbot')
    # ### end Alembic commands ###
