"""Adiciona tabela BibliotecaConteudo

Revision ID: 7fee99ed99e7
Revises: b8bd3eb2e1cb
Create Date: 2025-07-20 14:31:32.610599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fee99ed99e7'
down_revision = 'b8bd3eb2e1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteca_conteudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo_texto', sa.Text(), nullable=False),
    sa.Column('url_video', sa.String(length=255), nullable=True),
    sa.Column('url_imagem', sa.String(length=255), nullable=True),
    sa.Column('palavras_chave', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblioteca_conteudo')
    # ### end Alembic commands ###
