"""Adiciona a tabela LogAcessoPaciente para conformidade com LGPD

Revision ID: 83ca2152c00e
Revises: e0b637cee2de
Create Date: 2025-07-23 12:58:43.227268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ca2152c00e'
down_revision = 'e0b637cee2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_acesso_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeitura.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_acesso_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_acesso_paciente_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_acesso_paciente_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_acesso_paciente_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_acesso_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_acesso_paciente_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_log_acesso_paciente_timestamp'))
        batch_op.drop_index(batch_op.f('ix_log_acesso_paciente_paciente_id'))

    op.drop_table('log_acesso_paciente')
    # ### end Alembic commands ###
