"""Adiciona tabela Configuracao

Revision ID: b412764208f6
Revises: efd89b155c4e
Create Date: 2025-07-20 11:58:29.126884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b412764208f6'
down_revision = 'efd89b155c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracao_chave'), ['chave'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracao_chave'))

    op.drop_table('configuracao')
    # ### end Alembic commands ###
