"""Adiciona delegacao a tarefas

Revision ID: b8bd3eb2e1cb
Revises: 6b0d7361c6f3
Create Date: 2025-07-20 13:07:02.346535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd3eb2e1cb'
down_revision = '6b0d7361c6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atribuido_para_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['atribuido_para_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('atribuido_para_id')

    # ### end Alembic commands ###
