"""Adiciona status ao paciente e detalha consulta

Revision ID: c0b08d99af6a
Revises: 41f49ca81589
Create Date: 2025-07-20 11:09:18.997768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b08d99af6a'
down_revision = '41f49ca81589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('resumo_atendimento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consulta_status'), ['status'], unique=False)

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_paciente_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consulta_status'))

    op.drop_table('consulta')
    # ### end Alembic commands ###
