"""Adiciona tabela Tarefa

Revision ID: c3ece67ceaf6
Revises: b412764208f6
Create Date: 2025-07-20 12:09:55.424137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ece67ceaf6'
down_revision = 'b412764208f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefa_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefa_status'))

    op.drop_table('tarefa')
    # ### end Alembic commands ###
