"""Adiciona suporte a multi-tenancy com a tabela Prefeitura

Revision ID: e0b637cee2de
Revises: 2143bd6ebe02
Create Date: 2025-07-23 12:04:36.736855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b637cee2de'
down_revision = '2143bd6ebe02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefeitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cidade', sa.String(length=120), nullable=False),
    sa.Column('subdominio', sa.String(length=120), nullable=False),
    sa.Column('status_assinatura', sa.String(length=50), nullable=False),
    sa.Column('limite_consultas_mes', sa.Integer(), nullable=True),
    sa.Column('limite_atendimentos_mes', sa.Integer(), nullable=True),
    sa.Column('limite_usuarios_profissionais', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_cidade')
    )
    with op.batch_alter_table('prefeitura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prefeitura_subdominio'), ['subdominio'], unique=True)

    with op.batch_alter_table('biblioteca_conteudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_configuracao_chave'))
        batch_op.create_index(batch_op.f('ix_configuracao_chave'), ['chave'], unique=False)
        batch_op.create_unique_constraint('_chave_prefeitura_uc', ['chave', 'prefeitura_id'])
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('log_uso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('mensagem_chatbot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_mensagem_chatbot_chave'))
        batch_op.create_index(batch_op.f('ix_mensagem_chatbot_chave'), ['chave'], unique=False)
        batch_op.create_unique_constraint('_msg_chatbot_chave_prefeitura_uc', ['chave', 'prefeitura_id'])
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('paciente_telefone_whatsapp_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_paciente_cns'))
        batch_op.create_index(batch_op.f('ix_paciente_cns'), ['cns'], unique=False)
        batch_op.drop_index(batch_op.f('ix_paciente_cpf'))
        batch_op.create_index(batch_op.f('ix_paciente_cpf'), ['cpf'], unique=False)
        batch_op.create_unique_constraint('_cpf_prefeitura_uc', ['cpf', 'prefeitura_id'])
        batch_op.create_unique_constraint('_telefone_prefeitura_uc', ['telefone_whatsapp', 'prefeitura_id'])
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('termo_consentimento_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefeitura_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=False)
        batch_op.create_unique_constraint('_email_prefeitura_uc', ['email', 'prefeitura_id'])
        batch_op.create_foreign_key(None, 'prefeitura', ['prefeitura_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_email_prefeitura_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('termo_consentimento_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_telefone_prefeitura_uc', type_='unique')
        batch_op.drop_constraint('_cpf_prefeitura_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_paciente_cpf'))
        batch_op.create_index(batch_op.f('ix_paciente_cpf'), ['cpf'], unique=True)
        batch_op.drop_index(batch_op.f('ix_paciente_cns'))
        batch_op.create_index(batch_op.f('ix_paciente_cns'), ['cns'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('paciente_telefone_whatsapp_key'), ['telefone_whatsapp'])
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('mensagem_chatbot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_msg_chatbot_chave_prefeitura_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_mensagem_chatbot_chave'))
        batch_op.create_index(batch_op.f('ix_mensagem_chatbot_chave'), ['chave'], unique=True)
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('log_uso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_chave_prefeitura_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_configuracao_chave'))
        batch_op.create_index(batch_op.f('ix_configuracao_chave'), ['chave'], unique=True)
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('biblioteca_conteudo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prefeitura_id')

    with op.batch_alter_table('prefeitura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prefeitura_subdominio'))

    op.drop_table('prefeitura')
    # ### end Alembic commands ###
