"""Adiciona a tabela MagicLink para o portal do titular

Revision ID: e8f36eafdd07
Revises: 83ca2152c00e
Create Date: 2025-07-23 13:05:30.604951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f36eafdd07'
down_revision = '83ca2152c00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_link_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_link_token'))

    op.drop_table('magic_link')
    # ### end Alembic commands ###
