"""Adiciona tabela Documento

Revision ID: efd89b155c4e
Revises: c0b08d99af6a
Create Date: 2025-07-20 11:25:15.595929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd89b155c4e'
down_revision = 'c0b08d99af6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('hash_assinatura', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_tipo'))

    op.drop_table('documento')
    # ### end Alembic commands ###
